export const works=[
  { "title":"Escenas", "instrumentation":"flute solo", "year":2010, "duration":"5'", "genre":"solo" },
  { "title":"Tres Poemas de Alejandra Pizarnik", "instrumentation":"soprano and piano", "year":2011, "duration":"7'", "genre":"voice" },
  { "title":"Temas y Variaciones", "instrumentation":"flute, clarinet and bassoon", "year":2013, "duration":"6'", "genre":"chamber" },
  { "title":"Tres Poemas de Blanca Varela", "instrumentation":"mixed choir", "year":2013, "duration":"8'", "genre":"choir" },
  { "title":"String Quartet Nº1", "year":2014, "duration":"8'", "genre":"chamber" },
  { "title":"De Rebus Humanis", "instrumentation":"violin solo and small orchestra", "year":2015, "duration":"12'", "genre":"soloorch" },
  { "title":"Nuevas Escenas", "instrumentation":"full orchestra", "year":2017, "duration":"15'", "genre":"orch" },
  { "title":"Piano Trio Nº1", "instrumentation":"violin, cello and piano", "year":2018, "duration":"13'", "genre":"chamber" },
  { "title":"Dos Danzas", "instrumentation":"piano", "year":2018, "duration":"8'", "genre":"solo" },
  { "title":"Soliloquia inter Memorias", "instrumentation":"cello solo", "year":2019, "duration":"4'", "genre":"solo" },
  { "title":"Dos Crisoles", "instrumentation":"flute and string orchestra (string quintet)", "year":2019, "duration":"9'", "genre":"orch" },
  { "title":"Tres Danzas", "instrumentation":"orchestra (orchestration of Dos Danzas + 1)", "year":2019, "duration":"15'", "genre":"orch" },
  { "title":"Sonata", "instrumentation":"flute and piano", "year":2020, "duration":" ", "genre":"chamber" },
  { "title":"Ex Bosco, ad Arboretum", "instrumentation":"string orchestra", "year":2020, "duration":" ", "genre":"orch" },
  { "title":"Crepuscular", "instrumentation":"3 equal voices", "year":2020, "duration":"3", "genre":"choir" },
]